# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Python Package CI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git LFS
        run: |
          git lfs install

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          lfs: true

      - name: Pull LFS files for submodules
        run: |
          cd src/sense_voice_streaming_asr/models/speech_fsmn_vad_zh-cn-16k-common-onnx
          git lfs pull
          cd ../SenseVoiceSmall
          git lfs pull

      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build --wheel

      - name: Upload distributions artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  upload-to-release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download distributions from build job
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Upload assets to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

#  pypi-publish:
#    runs-on: ubuntu-latest
#    if: github.event_name == 'workflow_dispatch'
#    needs:
#      - build
#    permissions:
#      # IMPORTANT: this permission is mandatory for trusted publishing
#      id-token: write
#
#    # Dedicated environments with protections for publishing are strongly recommended.
#    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
#    environment:
#      name: pypi
#      url: https://pypi.org/p/sense-voice-streaming-asr
#
#    steps:
#      - name: Retrieve release distributions
#        uses: actions/download-artifact@v4
#        with:
#          name: release-dists
#          path: dist/
#
#      - name: Publish release distributions to PyPI
#        uses: pypa/gh-action-pypi-publish@release/v1
#        with:
#          packages-dir: dist/
